---
event_name_prefix: [WORK]

calendar_id: primary

color_hexes:
  - '#51b749' # dark green
  - '#7ae7bf' # light green

projects:
  - name: Client A
    hours_per_month: 30
    # Percentage of the project hours you work (out of your team)
    work_share: 0.3
    # For things like calls -- e.g. a 1 hour call each week with a client
    pre_booked_hours_per_week: 1

  - name: Client B
    hours_per_month: 30
    work_share: 1
    pre_booked_hours_per_week: 3

  - name: Client C
    hours_per_month: 30
    work_share: 0.5
    pre_booked_hours_per_week: 0.5
